apiVersion: v1
kind: Service
metadata:
  name: app-ui-service
  labels:
    name: app-ui-dev
    type: frontend
spec:
  type: NodePort
  ports:
    - targetPort: 3000
      port: 3000
      nodePort: 30333
  selector:
    app: app-ui
    type: frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-ui-deployment
  labels:
    app: app-ui
    type: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-ui
  template:
    metadata:
      labels:
        app: app-ui
        type: frontend
    spec:
      containers:
      - name: app-ui
        image: dgisolfi/app:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
